# This is the configuration for Travis CI, a free github-integrated service that runs this script for each pull request (if configured)

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# provides gcc, clang, make, scons, cmake
language: c++

# alternatives: gcc, clang, or both (as yaml list)
compiler: gcc

addons:
  apt:
    packages:
      - python3
      - python3-dev
      - python3-pip

before_install:
  # Don't touch source code directory
  - cd ..
  - wget https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz -O /tmp/cmake.tar.gz
  - tar xzf /tmp/cmake.tar.gz
  - export PATH=`pwd`/cmake-3.5.2-Linux-x86_64/bin/:${PATH}

install:
  # Install conan
  - sudo pip3 install conan
  # Automatic detection of your arch, compiler, etc.
  - conan user
  # Add repository with additional dependencies
  - conan remote add bintray-jakule https://api.bintray.com/conan/jakule/public-conan

script:
 - mkdir andiff-build
 - cd andiff-build
 - conan install ../andiff -s build_type=Release --build=missing
 - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ../andiff
 - cmake --build .
 - ctest -V
 - cpack -V

notifications:
  email: false
